# load libraries
library(shiny)
library(shinyWidgets)
library(RColorBrewer)
library(classInt)
library(plotly)
library(ggplot2)
library(ggthemes)
library(dplyr)
library(shinythemes)
library(ggiraph)
library(shinydashboard)
library(leaflet)

library(scales)
library(grid)
library(tmap)
library(sf)
library(spData)
library(tigris)
library(maps)
library(maptools)
library(mapproj)
library(rgeos)
library(geojsonio)
library(rgdal)
library(gapminder)
library(gdata)
library(tidyverse)
library(readxl)
library(janitor)
library(DT)

#______________________________________________________
#read in R data
#______________________________________________________
load("adm_pop_long.Rda")
load("mclc.Rda")
load("mclc_change.Rda")
load("mclc_datatable.Rda")
load("us_aea2.Rda")
load("df_adm.Rda")
load("df_pop.Rda")