---
title: "Info-graphics Quick AZ plots" 
description: "Last User: `r stringr::str_sub(getwd(), 10, stringr::str_locate(stringr::str_sub(getwd(), 10, -1), '/')[1]+10-2)`"
date: last-modified
date-format: "YYYY-MM-DD HH:mm:ss"
published-title: Last Modified
doi: "`r Sys.time()`"
doi-title: Last Ran
execute:
  echo: false
format: 
  html:
    page-layout: full
    fontsize: 0.9em
    fig-width: 12
    fig-height: 7
editor: source
self-contained: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false  

library(tidyverse)

box::use(
    box/admin
  , box/infograph
)
```


```{r}
#| label: import data 
REV_APS <- readRDS(file.path(admin$sp_data, "NCRP_REV_APS.RDS"))
#REV_SC  <- readRDS(file.path(admin$sp_data, "NCRP_REV_SC.RDS"))
```



::: {.panel-tabset}
<!-- start {.panel-tabset} ALLLL --> 



```{r}
IG_DF <- REV_APS$R %>% 
  filter(RACE %in% admin$lev_RACE[1:3]) %>% 
  filter(RPTYEAR == RECENT_YR) %>% 
  filter(!is.na(RRI), RRI != Inf) %>% 
  select(STATE, ABB, RPTYEAR, RACE, RRI, RECENT_YR) %>% 
  group_by(STATE) %>% 
  mutate(n_groups = sum(!is.na(RACE))) %>%
  ungroup() %>% 
  filter(n_groups > 1) %>% 
  filter(ABB != "DC")

#IG_DF$RRI |> summary()
```


```{r}
#| fig-height: 3.3
#| fig-width: 6
IG_DF_AZ <- IG_DF %>% filter(ABB == "AZ")

pmap(
  list(
      race    = IG_DF_AZ$RACE
    , rri_raw = IG_DF_AZ$RRI
    , state   = IG_DF_AZ$ABB
  )
  , infograph$create_infograph 
)




```



::: 
<!-- end {.panel-tabset} ALLLL --> 


