---
title: "NCRP Mock-Up: Revocations 2015-2019" 
date: "Last updated/ran: `r Sys.time()`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r, include = FALSE}
box::use(
    box/calc
  , box/admin
)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.height = 8, fig.width = 10)

library(tidyverse)
library(highcharter)
library(kableExtra)
library(reactable)
```



```{r}
CNTRTDF <- calc$combine_and_calcrates()
```
```{r}
#copy over from Mari's code, make some edits for these plots 

###app/dataframes.R
default_fonts <- c("Graphik")

#gcolors <- c("#D25E2D", "#EDB799", "#C7E8F5", "#236ca7", "#D6C246", "#dcdcdc")

gcolors <- c("#666666", "#D25E2D", "#236ca7", "#D6C246", "#EDB799", "#C7E8F5")

### app/functions.R
# custom highcharts theme for plots
hc_theme_jc2 <- hc_theme(
    #colors = c("#D25E2D", "#EDB799", "#C7E8F5", "#236ca7", "#D6C246", "#dcdcdc")
    chart = list(style = list(fontFamily = default_fonts, color = "#666666"))
  , title = list(align = "left", style = list(fontFamily = default_fonts, fontSize = "24px")) 
  , subtitle = list(align = "left", style = list(fontFamily = default_fonts, fontSize = "16px"))
  , legend = list(align = "left", verticalAlign = "top")
  , xAxis = list(
        gridLineColor = "transparent"
      , lineColor = "transparent"
      , minorGridLineColor = "transparent"
      , tickColor = "transparent"
    )
  # , yAxis = list(
  #       labels = list(enabled = FALSE)
  #     , gridLineColor = "transparent"
  #     , lineColor = "transparent"
  #     , minorGridLineColor = "transparent"
  #     , tickColor = "transparent"
  #     )
  , plotOptions = list(
         line = list(marker = list(enabled = FALSE), lineWidth = 3)
      # , spline = list(marker = list(enabled = FALSE))
      #  area = list(marker = list(enabled = FALSE))
      # , areaspline = list(marker = list(enabled = FALSE))
      # , arearange = list(marker = list(enabled = FALSE))
       , bubble = list(maxSize = "10%")
      )
)


rri_wline_dark <-  list(list(
      value  = 1
    , color  = "#666666"
    , width  = 2
    , zIndex = 4
    , dashStyle = "Dash" #https://api.highcharts.com/class-reference/Highcharts#.DashStyleValue
    , label = list(
        text = "White (ref. group)"
      , rotation = 0
      , style = list(
          color = "#666666"
        , fontWeight = "bold"
        ) #end style list
    ) #end label list
  )) #end doublelist


rri_wline_lite <-  list(list(
      value  = 1
    , color  = "#666666"
    , width  = 2
    , zIndex = 4
    , dashStyle = "Dash" #https://api.highcharts.com/class-reference/Highcharts#.DashStyleValue
    , label = list(
        text = "White (ref. group)"
      , rotation = 0
      , style = list(
          color = "#666666"
        , fontWeight = "bold"
        ) #end style list
    ) #end label list
  )) #end doublelist



refgroup <- function(hc, col = "dark", dash = "Dash", width = 2, type = "line", lineColor = NA){
  
  thisColor <- case_when(
      col == "dark"  ~ "#666666"
    , col == "light" ~ "#dcdcdc"
    , TRUE           ~ col
  )
  
  #https://api.highcharts.com/class-reference/Highcharts#.DashStyleValue
  if (is.na(dash) | !dash %in% c('Dash', 'DashDot',  'Dot',  'LongDash',  'LongDashDot',  'LongDashDotDot',  'ShortDash',  'ShortDashDot',  'ShortDashDotDot', 'ShortDot',  'Solid')){
    thisDash <- "Dash"
    warning("Dash Style not available")
  } else {
    thisDash <- dash 
  }
  
  
  hc_add_series(
    hc
        , data = data.frame(x = 2015:2019, y = 1)
        , type = type
        , color = thisColor
        , dashStyle = thisDash  
        , name = "White (ref. group)"
        , marker = FALSE
        , lineWidth = width
        , lineColor = ifelse(is.na(lineColor), thisColor, lineColor)
)
}

```

# {.tabset} 

All examples are shown with CA.  

**UPDATES**

- only show area RRI chart
- add REVCNT and RATE_100K to tooltip in RRI chart 
- add table with all 3 values 

```{r}
ABB <- "CA"
VAR <- "REVCNT"
```

```{r}
fnc_highchart_ROline <- function(ABB, VAR){
  
  ptfmt <- case_when(
      VAR == "REVCNT"    ~ "{point.VAR:,.0f}" #0 decimal places 
    , VAR == "RATE_1K"   ~ "{point.VAR:,.2f} per 1,000" #2 decimal places 
    , VAR == "RATE_100K" ~ "{point.VAR:,.1f} per 100,000" #1 decimal place
    , VAR == "RATE_1MIL" ~ "{point.VAR:,.1f} per 1,000,000" #1 decimal place
    , VAR == "RRI"       ~ "{point.RACE} is {point.VAR:,.1f}x as likely as White" #1 decimal place
    )
  
  if (substr(VAR, 1, 3) == "RRI"){
    theseRE   <- admin$lev_RACE[1:3] #only include black and hispanic 
    theseCols <- gcolors[1:3]
  } else {
    theseRE <- admin$lev_RACE[1:4] #White, Black, Hispanic, Other 
    theseCols <- gcolors[1:4]
  }
  
  plotdata <-  CNTRTDF$OR %>% 
    filter(ABB == !!ABB) %>% 
    rename("VAR" = !!VAR) %>% 
    filter(RACE %in% theseRE) %>% 
    filter(!OFFGENERAL %in% admin$lev_OFFGENERAL[-c(1:4)])#REMOVE OTHER/MISSING OFFGENERAL 
    
  map(admin$lev_OFFGENERAL[1:4], function(OG){
    
    plotdata %>% 
      filter(OFFGENERAL == OG) %>% 
      hchart("line"
        , hcaes(x = RPTYEAR, y = VAR, group = RACE)
        , color = theseCols
        , tooltip = list(pointFormat = ptfmt)
      ) %>% 
      hc_title(text = OG) %>% 
      hc_yAxis(min = 0, max = max(plotdata$VAR, na.rm = TRUE), title = list(text = "")) %>% 
      hc_xAxis(title = list(text = "")) %>% 
      hc_add_theme(hc_theme_jc2)
  }) %>% 
  hw_grid(rowheight = 350, ncol = 4) %>% 
    htmltools::browsable()
  
}

# fnc_highchart_ROline("CA", "REVCNT")


```



## Revocations 


### Relative Rate Index of Revocations 

```{r, fig.align="center"}
og_all_name <- "Any category"

VAR <- "RRI"

  ptfmt <- "{point.RACE} is {point.VAR:,.1f}x as likely as White<br>Rate per 100,000: {point.RATE_100K:,.1f}<br>Revocation count: {point.REVCNT}" #1 decimal place
  theseRE   <- admin$lev_RACE[2:3] #only include black and hispanic 
  theseCols <- gcolors[2:3]

  
  plotdata <-  CNTRTDF$R %>% 
    filter(ABB == !!ABB) %>% 
    rename("VAR" = !!VAR) 
    
    
    bh <- plotdata %>% filter(RACE %in% theseRE)
    #should all == 1,, instead of just putting as 1, leave as is (will help check calcs are done right)
    w  <- plotdata %>% filter(RACE == admin$lev_RACE[1]) %>% select(x = RPTYEAR, y = VAR, REVCNT, RATE_100K)
    
    hc_all <- hchart(bh, "area"
        , hcaes(x = RPTYEAR, y = VAR, group = RACE)
        , color = theseCols
        , tooltip = list(pointFormat = ptfmt)
        , marker = FALSE
        , lineColor = "white"
        , lineWidth = 1
      ) %>% 
        hc_add_series(
          data = w
        , type = "area"
        , color = "#dcdcdc"
        , dashStyle = "Solid"  
        , name = "White (ref. group)"
        , marker = FALSE
        , lineWidth = 1
        , lineColor = "white"
        , tooltip = list(pointFormat ="White (Reference Group) = 1<br>Rate per 100,000: {point.RATE_100K:,.1f}<br>Revocation count: {point.REVCNT}" )
      ) %>% 
      #refgroup(col = "light", dash = "Solid", width = 1, type = "area", lineColor = "white") %>% 
      hc_title(text = og_all_name) %>% 
      hc_yAxis(min = 0
               , max = max(plotdata$VAR, na.rm = TRUE)
               , title = list(text = "")
               , labels  = list(format = "{text}x")
      ) %>% 
      hc_xAxis(title = list(text = "")) %>% 
      hc_add_theme(hc_theme_jc2) %>% 
      hc_size(width= 225, height = 350)
    
    hc_blank <- highchart() %>% hc_size(width= 337.5, height = 350)
    
hw_grid(list(hc_blank, hc_all, hc_blank), rowheight = 350, ncol = 3)
```


```{r}
VAR <- "RRI"

  ptfmt <- "{point.RACE} is {point.VAR:,.1f}x as likely as White<br>Rate per 100,000: {point.RATE_100K:,.1f}<br>Revocation count: {point.REVCNT}" #1 decimal place
  theseRE   <- admin$lev_RACE[2:3] #only include black and hispanic 
  theseCols <- gcolors[2:3]

  
  plotdata <-  CNTRTDF$OR %>% 
    filter(ABB == !!ABB) %>% 
    rename("VAR" = !!VAR) %>% 
    filter(!OFFGENERAL %in% admin$lev_OFFGENERAL[-c(1:4)])#REMOVE OTHER/MISSING OFFGENERAL 
    
  map(admin$lev_OFFGENERAL[1:4], function(OG){
    
    bh <- plotdata %>% filter(OFFGENERAL == OG, RACE %in% theseRE)
    #should all == 1,, instead of just putting as 1, leave as is (will help check calcs are done right)
    w  <- plotdata %>% filter(OFFGENERAL == OG, RACE == admin$lev_RACE[1]) %>% select(x = RPTYEAR, y = VAR, REVCNT, RATE_100K)
    
    hchart(bh, "area"
        , hcaes(x = RPTYEAR, y = VAR, group = RACE)
        , color = theseCols
        , tooltip = list(pointFormat = ptfmt)
        , marker = FALSE
        , lineColor = "white"
        , lineWidth = 1
      ) %>% 
        hc_add_series(
          data = w
        , type = "area"
        , color = "#dcdcdc"
        , dashStyle = "Solid"  
        , name = "White (ref. group)"
        , marker = FALSE
        , lineWidth = 1
        , lineColor = "white"
        , tooltip = list(pointFormat ="White (Reference Group) = 1<br>Rate per 100,000: {point.RATE_100K:,.1f}<br>Revocation count: {point.REVCNT}" )
      ) %>% 
      #refgroup(col = "light", dash = "Solid", width = 1, type = "area", lineColor = "white") %>% 
      hc_title(text = OG) %>% 
      hc_yAxis(min = 0
               , max = max(plotdata$VAR, na.rm = TRUE)
               , title = list(text = "")
               , labels  = list(format = "{text}x")
      ) %>% 
      hc_xAxis(title = list(text = "")) %>% 
      hc_add_theme(hc_theme_jc2)
  }) %>% 
  hw_grid(rowheight = 350, ncol = 4) %>% 
    htmltools::browsable()
```




### Tables


```{r}

fmt_mdig <- function(x, mdig = 1){
  format(round(x, digits = mdig), nsmall = mdig, trim = TRUE)
}

table_numeric <- bind_rows(
    CNTRTDF$R %>% 
      filter(ABB == !!ABB, RACE %in% admin$lev_RACE[1:3]) %>% 
      select(RPTYEAR, RACE, REVCNT, RATE_100K, RRI) %>% 
      mutate(OFFGENERAL = og_all_name) 
  , CNTRTDF$OR %>% 
      filter(ABB == !!ABB, OFFGENERAL %in% admin$lev_OFFGENERAL[1:4], RACE %in% admin$lev_RACE[1:3]) %>% 
      select(RPTYEAR, OFFGENERAL, RACE, REVCNT, RATE_100K, RRI)
) %>%
  pivot_longer(cols = c(REVCNT, RATE_100K, RRI), names_to = "METRIC", values_to = "VALUE") %>%
  pivot_wider(names_from = RPTYEAR, values_from = VALUE) %>% 
  mutate(
      RACE = as.character(RACE)
    , METRIC = factor(METRIC, levels = c("RRI", "RATE_100K", "REVCNT"))
    , OFFGENEARL = factor(OFFGENERAL, levels = c(og_all_name, admin$lev_OFFGENERAL))
  ) %>% 
  select(METRIC, OFFGENEARL, RACE, paste0(2015:2019)) %>% 
  arrange(METRIC, OFFGENEARL, RACE)


rm_count <- JS("function(cellInfo) {return cellInfo.value}")


reactable_1metric <- function(metric, expand = TRUE){
  
  if (metric == "RRI"){
    filtered_table <- table_numeric %>% filter(METRIC == metric, RACE %in% admin$lev_RACE[2:3])
  } else { 
    filtered_table <- table_numeric %>% filter(METRIC == metric)
  }
  
  filtered_table %>% 
  filter(METRIC == metric) %>% 
  mutate_at(
      vars(paste0(2015:2019))
    , ~case_when(
        METRIC == "REVCNT"                          ~ scales::comma(., accuracy = 1)
      , METRIC == "RATE_100K"                       ~ fmt_mdig(.)
      , METRIC == "RRI" & RACE == admin$lev_RACE[1] ~ "Ref. Group"
      , METRIC == "RRI" & RACE != admin$lev_RACE[1] ~ paste0(fmt_mdig(.), "x")
    )
  ) %>% 
  select(-METRIC) %>% 
  reactable(
    theme = reactableTheme(cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center"))
    , defaultColDef = colDef(align = "right", minWidth = 70)
    , compact = TRUE
    , columns = list(
          "OFFGENEARL" = colDef(name = "Offense Category", align = "left", minWidth = 125, grouped = rm_count)
        , "RACE"       = colDef(name = "Race"            , align = "left", minWidth =  70)
    )
    , highlight = TRUE 
    , pagination = FALSE
    , groupBy = c("OFFGENEARL")
    , defaultExpanded = expand
  )
  
}



```


##### Relative Rate Index (White Reference Group)

```{r}
reactable_1metric("RRI")
```


##### Rate per 100,000 People in Population 

```{r}
reactable_1metric("RATE_100K", expand = FALSE)
```

##### Revocation Counts

```{r}
reactable_1metric("REVCNT", expand = FALSE)
```





